const DEFAULT_SETTINGS = {
  polling_interval_seconds: "5",
  idle_threshold_seconds: "90",
  data_retention_days: "never",
  launch_on_login: "true",
  start_minimized: "true",
  close_to_tray: "true",
  first_run_complete: "false",
  focus_session_duration_minutes: "25",
  focus_session_break_minutes: "5",
  productivity_score_goal: "70",
  productivity_min_minutes: "10",
  pomodoro_sound_enabled: "true",
  pomodoro_sound_type: "bell",
  pomodoro_sound_volume: "80",
  break_overlay_enabled: "true",
};

const DEFAULT_CATEGORIES = {
  code: "Development",
  "code-oss": "Development",
  codium: "Development",
  firefox: "Browser",
  "firefox-esr": "Browser",
  chromium: "Browser",
  "google-chrome-stable": "Browser",
  "Google-chrome": "Browser",
  "google-chrome": "Browser",
  chrome: "Browser",
  slack: "Communication",
  discord: "Communication",
  telegram: "Communication",
  whatsapp: "Communication",
  "whatsapp-linux-app": "Communication",
  spotify: "Entertainment",
  vlc: "Entertainment",
  terminal: "System",
  "gnome-terminal": "System",
  kitty: "System",
  alacritty: "System",
  nautilus: "System",
  thunar: "System",
  gimp: "Creative",
  inkscape: "Creative",
  // Windows apps
  msedge: "Browser",
  devenv: "Development",
  notepad: "Productivity",
  explorer: "System",
  powershell: "System",
  pwsh: "System",
  cmd: "System",
  WindowsTerminal: "System",
  Teams: "Communication",
  Zoom: "Communication",
  WINWORD: "Productivity",
  EXCEL: "Productivity",
  POWERPNT: "Productivity",
};

// App name alias groups — keeps category/limit rules in sync across
// desktop environments that report different names for the same app.
const APP_ALIASES = {
  "google-chrome":        ["Google-chrome", "google-chrome", "google-chrome-stable", "chrome"],
  "google-chrome-stable": ["Google-chrome", "google-chrome", "google-chrome-stable", "chrome"],
  "chrome":               ["Google-chrome", "google-chrome", "google-chrome-stable", "chrome"],
  "whatsapp":             ["whatsapp-linux-app", "whatsapp"],
  "whatsapp-linux-app":   ["whatsapp-linux-app", "whatsapp"],
};

module.exports = { DEFAULT_SETTINGS, DEFAULT_CATEGORIES, APP_ALIASES };
